version: '3'
services:
  client-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    # networks:
    #   - brain-dump-network

  server-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # networks:
    #   - brain-dump-network

# networks:
#   brain-dump-network: